version: '3.7'

services:

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    ports:
      - ${PORTAINER_PORT}:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data

  terkin:
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
    image: debian/buster-slim
    restart: unless-stopped
    volumes:
      - ../terkin-datalogger:/opt/terkin-datalogger
    stdin_open: true
    tty: true

  mosquitto:
    image: eclipse-mosquitto:${MOSQUITTO_IMAGE_VERSION}
    init: true
    restart: unless-stopped
    ports:
      - ${MOSQUITTO_MQTT_PORT}:1883
      - ${MOSQUITTO_WS_PORT}:9001
    volumes:
      - ${VOLUMES_DIR}/mosquitto/conf:/mosquitto/config
      - ${VOLUMES_DIR}/mosquitto/data:/mosquitto/data
      - ${VOLUMES_DIR}/mosquitto/log:/mosquitto/log

  influxdb:
    image: influxdb:${INFLUXDB_IMAGE_VERSION}
    init: true
    restart: unless-stopped
    ports:
      - ${INFLUXDB_HTTP_PORT}:1883
    volumes:
      - ${VOLUMES_DIR}/influxdb/data:/var/lib/influxdb
      - ${VOLUMES_DIR}/influxdb/conf/influxdb.conf:/etc/influxdb/influxdb.conf:ro

  grafana:
    image: grafana/grafana:${GRAFANA_IMAGE_VERSION}
    init: true
    user: "1026"
    restart: unless-stopped
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ${VOLUMES_DIR}/grafana/data:/var/lib/grafana
      - ${VOLUMES_DIR}/grafana/log:/var/log/grafana
    depends_on: 
      - influxdb

  kotori:
    image: daqzilla/kotori:${KOTORI_IMAGE_VERSION}
    restart: unless-stopped
    ports:
      - ${KOTORI_PORT}:24642
    command: "kotori --config /etc/kotori/kotori.ini"
    volumes:
      - ${VOLUMES_DIR}/kotori/conf:/etc/kotori
    depends_on:
      - mosquitto
      - influxdb
      - grafana
  mongodb:
    image: mongo:${MONGODB_IMAGE_VERSION}
    init: true
    restart: always
    volumes:
      - ${VOLUMES_DIR}/mongodb/data:/data/db
      - ${VOLUMES_DIR}/mongodb/log:/var/log/mongodb
  redis:
    image: redis:${REDIS_IMAGE_VERSION}
    init: true
    restart: always
    volumes:
      - ${VOLUMES_DIR}/redis/data:/data
  putsreq:
    image: daqzilla/putsreq:${PUTSREQ_IMAGE_VERSION}
    restart: always
    tty: true
    stdin_open: true
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    ports:
      - '${PUTSREQ_PORT}:3000'
    environment:
      - RAILS_ENV=production
      - MONGOLAB_URI=mongodb://mongodb
      - REDIS_URL=redis://redis
      - DEVISE_SECRET_KEY=123
      - SECRET_TOKEN=123
    volumes:
      - ${VOLUMES_DIR}/putsreq/environments:/app/config/environments
    depends_on:
      - mongodb
      - redis
      - kotori
  putsreq_reverse_proxy:
    image: nginx
    init: true
    restart: always
    volumes:
      - ${VOLUMES_DIR}/nginx/templates:/etc/nginx/templates
      - ${VOLUMES_DIR}/nginx/log:/var/log/nginx
    ports:
      - "9090:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - PUTSREQ_BUCKET=<BUCKET_ID>
    depends_on:
      - putsreq


